name: wazo-calld-queue
namespace: sboily
version: 0.0.4
author: Sylvain Boily
display_name: Queue API and events
min_wazo_version: 22.06
tags:
  - experimental
  - queue
homepage: https://github.com/sboily/wazo-calld-queue
