name: wazo-calld-queue
namespace: mwolff44
version: 2.0.0
author: Sylvain Boily & Mathias WOLFF
display_name: Queue API and events
min_wazo_version: 25.02
tags:
  - queue
homepage: https://github.com/mwolff44/wazo-calld-queue
